Order components and dependencies by purl and ref to have reproducible output
CycloneDX/cyclonedx-gradle-plugin pull request #457
Opened 2024-06-19 12:36 UTC by emirmx

As the components and dependencies are stored in HashSet and HashMap when converted to lists, the order is not well defined and seems to change from time to time, especially when run on different computers.

In this PR, components and dependencies are sorted before the BOM is written to have the same order given same dependencies.

2024-06-19 22:34 UTC, skhokhlov commented
You can just use TeeSet instead of HashSet https://docs.oracle.com/javase/8/docs/api/java/util/TreeSet.html

2024-06-20 07:59 UTC, emirmx commented
> You can just use TreeSet instead of HashSet https://docs.oracle.com/javase/8/docs/api/java/util/TreeSet.html

Thanks, way better. Changed.

2024-07-03 07:56 UTC, emirmx commented
Hi. Is there a time-frame for PR's to be reviewed/merged? Also, for the releases?

2024-07-31 12:58 UTC, skhokhlov requested changes
I think this https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L398 can be removed now

2024-07-31 22:33 UTC, emirmx commented
> I think this https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L398 can be removed now

Sorry, could not tie your comment to the changes in the PR. Can you elaborate?

2024-08-01 08:48 UTC, emirmx commented
> I think this https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/master/src/main/java/org/cyclonedx/gradle/CycloneDxTask.java#L398 can be removed now

Though I still do not see the connection, I simplified the code in createBom a bit more within two additional commits.

2024-08-01 11:00 UTC, skhokhlov approved these changes
Sorry, the code moved a little bit. I meant this https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/457/files#diff-7d5ff0e9f240ba234a7a8e596f574d6fe41631e6fb16f8a1d2a252a6ae5ac72fL413 which is removed now. Thank you!

2024-08-01 11:01 UTC, merged