fix: sort bom components and dependencies
CycloneDX/cyclonedx-gradle-plugin pull request #549
Opened 2024-12-09 21:40 UTC by jeremylong

While there is absolutely no requirement to do this - it makes testing easier (at least for me). As you make simple changes in the plugin or project using the plugin by sorting the components and dependencies it makes simple file compares much easier.

2024-12-10 16:39 UTC, barblin commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
> +    private static void sortBom(final Bom bom) {
Would there be value in adding an opt-out or opt-in parameter? I don't know if its relevant, but it would change existing SBOMs and would make comparing one sbom version to another at least "harder". At least visualizing diffs.

If we have a sorting in the SBOM, it would be great if we could control for which field we want to sort. When I read that there is a sorting feature, I thought it would be by dependency name, but now I saw it will be PURL identifier and ref.

2024-12-10 16:39 UTC, barblin commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
> +    private static void sortBom(final Bom bom) {
Because it could affect the overall performance, opting out could be benefitial for some use-cases

2024-12-10 16:39 UTC, barblin commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
Missing tests

2024-12-11 13:40 UTC, jeremylong commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
> +    private static void sortBom(final Bom bom) {
The reason for the sorting is that there is no ordering. Changing a dependency in the project being scanned can vastly change the order in which dependencies are shown - as such I would love to add ordering. Other cycloneDx plugins [sort the dependencies](https://github.com/search?q=repo%3ACycloneDX%2Fcyclonedx-cocoapods%20sort&type=code) as well.

If others want a configuration option I can add it. However, I do not believe it is needed. I'll let @skhokhlov decide.

2024-12-11 13:41 UTC, jeremylong commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
This is just sorting - I didn't think this needed an explicit test.

2024-12-12 12:17 UTC, skhokhlov commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
> +        sortBom(bom);
Components and dependencies in the BOM are already sorted by using TreeSet here https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/ba5369b4f3792b9fcaf3237f26f75b0cd7014c53/src/main/java/org/cyclonedx/gradle/SbomBuilder.java#L95-L96. 

If you want to change the order, it must be done [here for components](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/ba5369b4f3792b9fcaf3237f26f75b0cd7014c53/src/main/java/org/cyclonedx/gradle/model/ComponentComparator.java) and [here for dependencies](https://github.com/CycloneDX/cyclonedx-gradle-plugin/blob/ba5369b4f3792b9fcaf3237f26f75b0cd7014c53/src/main/java/org/cyclonedx/gradle/model/DependencyComparator.java)

2024-12-12 12:20 UTC, skhokhlov commented on src/main/java/org/cyclonedx/gradle/utils/CycloneDxUtils.java
> +    private static void sortBom(final Bom bom) {
We already use TreeSet for components and dependencies, so there will be no performance degradation if you keep using it.

2024-12-12 12:22 UTC, skhokhlov requested changes
I believe that sorting components based on purl instead of bom-ref makes sense, but me done when plugin is collecting components, not afterwards.

2024-12-12 12:50 UTC, jeremylong commented
I'm not sure how feasible sorting on insert would be updating just the plugin. The lists we are sorting are contained in `org.cyclonedx.model` which is provided by [cyclonedx-core-java](https://github.com/CycloneDX/cyclonedx-core-java). To sort on insert we would need to update the core-java implementation to use sorted lists and and implement comparable on the types to be sorted. In addition, just from a performance standpoint sorting afterwards is slightly faster.

@skhokhlov let me know if you want me to close this PR and open one against the cyclonedx-core-java library.

2024-12-12 13:05 UTC, skhokhlov commented
@jeremylong it doesn't require changes for the core library because all the components are collected here with sorted sets and then they are just converted to regular lists, but the order is preserved. Please see my comment https://github.com/CycloneDX/cyclonedx-gradle-plugin/pull/549#discussion_r1881959696, it's just a single line change.

2024-12-12 13:06 UTC, jeremylong commented
Sorry - this PR was opened based on the old 1.x implementation that did not sort the output. Closing this PR as I missed the use of TreeSort. I don't think we need to adjust from `bom-ref` to `purl` - as they are almost, if not always, equal.

2024-12-12 13:06 UTC, closed without merging